---
title: "reading_data_from_the_web"
author: "Wenzhao Wu"
date: "10/20/2020"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)
library(httr)


knitr::opts_chunk$set(
  fig.width = 12,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Scrape a tables

read in the html

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

extract the table(s); focus on the first one

```{r}
drug_use_html %>%
  html_nodes(css = "table")
```

```{r}
table_marj = 
  drug_use_html %>% 
  html_nodes(css = "table") %>% 
  first() %>%
  html_table() %>%
  slice(-1) %>% 
  as_tibble()

table_marj
```
# Learning assessment

```{r}
url_i = ("https://www.bestplaces.net/cost_of_living/city/new_york/new_york")

cost_living_html = read_html(url_i)

cost_living_html
```

```{r}
table_cost = 
  cost_living_html %>% 
  html_nodes(css = "table") %>%
  first() %>%
  html_table(header = T) 
  
table_cost
```

## Star Wars Movie info

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

grab elements that I want

```{r}
title_vec = 
  swm_html %>%
  html_nodes(css = ".lister-item-header a") %>%
  html_text()

gross_rev_vec = 
  swm_html %>%
  html_nodes(css = ".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

runtime_vec = 
  swm_html %>%
  html_nodes(css = ".runtime") %>%
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```

# Learning assessment

```{r}
review_html = read_html("https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1")

```

```{r}
review_title = 
  review_html %>%
  html_nodes(css = ".a-text-bold span") %>%
  html_text()

profile_vec = 
  review_html %>%
  html_nodes(css = "#cm_cr-review_list .a-profile-name") %>%
  html_text()

review_df = 
  tibble(customers = profile_vec,
         reviews = review_title)
review_df
```

## Get some water data

This is coming from an API

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")
```

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```

some data aren't so nice

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name
poke$height
poke$abilities
```

